[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "https://aureum.netlify.app/*"
  to = "https://www.valcon-medical.com/
  force = true

[[redirects]]
  from = "https://aureum.netlify.app/"
  to = "https://www.valcon-medical.com/
  force = true

[[redirects]]
  from = "https://aureum.netlify.app"
  to = "https://www.valcon-medical.com/
  force = true

  [build]
  publish = "_site"
  command = "eleventy"